set(
	sources ${sources}
	src/Main.cpp
	src/Window.cpp
	src/Window.h
	src/WinAPI.h
	src/ScreenshotHandler.h
	src/ScreenshotHandler.cpp
	src/HRSException.cpp
	src/HRSException.h
	src/Settings.h
	src/Resolution.h
	src/logger.cpp
	src/logger.h
	src/HRS.cpp
	src/HRS.h
	src/WindowsMessageMap.h
	src/WindowsMessageMap.cpp
	src/Renderer.cpp
	src/Renderer.h
)